/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ie.orderofmalta;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class AccountForm extends javax.swing.JFrame {

    /**
     * Creates new form AccountForm
     */
    
    private ArrayList<Account> account;
    protected String accArr[];
    
    public AccountForm() {
        accArr = new String[100];
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        account = new ArrayList<Account>();
        //account.clear();
        loadFile();
        jComboBox1ActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        accNumLbl = new javax.swing.JLabel();
        accPurposeLbl = new javax.swing.JLabel();
        bicNumLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        accTypeLbl = new javax.swing.JLabel();
        sig1Lbl = new javax.swing.JLabel();
        sig2Lbl = new javax.swing.JLabel();
        sig3Lbl = new javax.swing.JLabel();
        sig4Lbl = new javax.swing.JLabel();
        accPurposeTxt = new javax.swing.JTextField();
        bicNumTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        phoneTxt = new javax.swing.JTextField();
        accTypeTxt = new javax.swing.JTextField();
        sig1txt = new javax.swing.JTextField();
        sig2Txt = new javax.swing.JTextField();
        sig3Txt = new javax.swing.JTextField();
        sig4Txt = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        accNumTxt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        updateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        titleLbl.setText("List of Unit Accounts");

        accNumLbl.setText("Account (IBAN) No:");

        accPurposeLbl.setText("Account Purpose:");

        bicNumLbl.setText("BIC No:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Financial Institution Information");

        nameLbl.setText("Name:");

        addressLbl.setText("Address:");

        phoneLbl.setText("Phone No:");

        accTypeLbl.setText("Account Type:");

        sig1Lbl.setText("Signature 1:");

        sig2Lbl.setText("Signature 2:");

        sig3Lbl.setText("Signature 3:");

        sig4Lbl.setText("Signature 4:");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Account 1", "Account 2", "Account 3", "Account 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl)
                            .addComponent(addressLbl)
                            .addComponent(phoneLbl)
                            .addComponent(sig1Lbl)
                            .addComponent(sig2Lbl)
                            .addComponent(sig3Lbl)
                            .addComponent(sig4Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(addressTxt)
                            .addComponent(phoneTxt)
                            .addComponent(sig4Txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(sig3Txt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sig2Txt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sig1txt, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accNumLbl)
                            .addComponent(accPurposeLbl)
                            .addComponent(accTypeLbl)
                            .addComponent(bicNumLbl))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bicNumTxt)
                            .addComponent(accPurposeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(accTypeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(accNumTxt))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLbl)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accNumLbl)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accPurposeLbl)
                    .addComponent(accPurposeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accTypeLbl)
                    .addComponent(accTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bicNumLbl)
                    .addComponent(bicNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLbl)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sig1Lbl)
                    .addComponent(sig1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sig2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sig2Lbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sig3Lbl)
                    .addComponent(sig3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sig4Lbl)
                    .addComponent(sig4Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(544, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        private void loadFile() {                                        
        try {
           ObjectInputStream in = new ObjectInputStream(new FileInputStream("AccountDetails.dat"));
            Account accTemp;
            Account acc;
            account.clear();
            while (true) {
                accTemp = (Account) in.readObject();
                
                acc = new Account();
                //if(jComboBox1.getSelectedItem().equals(accTemp.getAccNum())){
                //load data from AccountDetails.dat to Account class
                acc.setIBANNum(accTemp.getIBANNum());
                acc.setAccountPurpose(accTemp.getAccountPurpose());
                acc.setAccType(accTemp.getAccType());
                acc.setBICNum(accTemp.getBICNum());
                acc.setBankName(accTemp.getBankName());
                acc.setBankAdd(accTemp.getBankAdd());
                acc.setBankphone(accTemp.getBankphone());
                acc.setSig1(accTemp.getSig1());
                acc.setSig2(accTemp.getSig2());
                acc.setSig3(accTemp.getSig3());
                acc.setSig4(accTemp.getSig4());
                acc.setAccNum(accTemp.getAccNum());
                
                //save to arraylist
                //account.clear();
                account.add(acc);
                
                /*//set txt fields to entries from saved object
                accNumTxt.setText(accTemp.getIBANNum());
                accPurposeTxt.setText(accTemp.getAccountPurpose());
                bicNumTxt.setText(accTemp.getBICNum());
                nameTxt.setText(accTemp.getBankName());
                addressTxt.setText(accTemp.getBankAdd());
                phoneTxt.setText(accTemp.getBankphone());
                accTypeTxt.setText(accTemp.getAccType());
                sig1txt.setText(accTemp.getSig1());
                sig2Txt.setText(accTemp.getSig2());
                sig3Txt.setText(accTemp.getSig3());
                sig4Txt.setText(accTemp.getSig4());
                //}*/
                
            }
            
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Class Not Found Exception: " + e);
        } catch (EOFException ex) {
            //end of file exception will be thrown when end of file reached
            //do nothing with this exception
            //JOptionPane.showMessageDialog(null, "End of File Reached");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "IOError: " + e);
        }
        //load accountArray method to save a/c number to String for use in payments/income form
       accountArray();
       //System.out.println("Load file array: " + accArr[0] +" "+ accArr[1] +" "+ accArr[2] +" "+ accArr[3]);
        
    } 
    private void accountArray(){
        for(int i = 0; i <account.size(); i++){
            Account temp;
            temp = account.get(i);
            accArr[i] = temp.getIBANNum();
        }
    }
    
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        
        accNumTxt.setText("");
        accPurposeTxt.setText("");
        bicNumTxt.setText("");
        nameTxt.setText("");
        addressTxt.setText("");
        phoneTxt.setText("");
        accTypeTxt.setText("");
        sig1txt.setText("");
        sig2Txt.setText("");
        sig3Txt.setText("");
        sig4Txt.setText("");
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if(accNumTxt.getText().equals("") | accTypeTxt.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter Account Number and Account Type at minimum!");
        }
        else{
            
        
            if(account.size() == 0){
                //create instance of Account object 
                Account acc = new Account();

                //add txt fields to Account
                acc.setIBANNum(accNumTxt.getText());
                acc.setAccountPurpose(accPurposeTxt.getText());
                acc.setAccType(accTypeTxt.getText());
                acc.setBICNum(bicNumTxt.getText());
                acc.setBankName(nameTxt.getText());
                acc.setBankAdd(addressTxt.getText());
                acc.setBankphone(phoneTxt.getText());
                acc.setSig1(sig1txt.getText());
                acc.setSig2(sig2Txt.getText());
                acc.setSig3(sig3Txt.getText());
                acc.setSig4(sig4Txt.getText());
                acc.setAccNum(jComboBox1.getSelectedItem().toString());

                //loadBtnActionPerformed(null);
                //add to arraylist
                account.add(acc);
            }
   
                else if(!jComboBox1.getSelectedItem().equals("Account 1") | !jComboBox1.getSelectedItem().equals("Account 2") | 
                        !jComboBox1.getSelectedItem().equals("Account 3") | !jComboBox1.getSelectedItem().equals("Account 4")){           
               
                Account acc = new Account();

                //add txt fields to Account
                acc.setIBANNum(accNumTxt.getText());
                acc.setAccountPurpose(accPurposeTxt.getText());
                acc.setAccType(accTypeTxt.getText());
                acc.setBICNum(bicNumTxt.getText());
                acc.setBankName(nameTxt.getText());
                acc.setBankAdd(addressTxt.getText());
                acc.setBankphone(phoneTxt.getText());
                acc.setSig1(sig1txt.getText());
                acc.setSig2(sig2Txt.getText());
                acc.setSig3(sig3Txt.getText());
                acc.setSig4(sig4Txt.getText());
                acc.setAccNum(jComboBox1.getSelectedItem().toString());

                //loadBtnActionPerformed(null);
                //add to arraylist
                account.add(acc);
                   }
                
            
        
         //this was below catch blocks
          
                //Save
                try{
                    ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("AccountDetails.dat"));


                    for(int i = 0; i < account.size(); i++){
                        out.writeObject(account.get(i));
                        //out.writeObject(acc);
                        //close stream

                       }
                     out.close();  
                }
                catch(EOFException e){
                        //End of file always throws exception, do nothing with this
                        }
                catch(FileNotFoundException ev){
                        JOptionPane.showMessageDialog(null, "File Not Found Exception: "+ ev);
                        }
                catch(IOException evn){
                        JOptionPane.showMessageDialog(null, "IOException: "+ evn);
                        }
                JOptionPane.showMessageDialog(rootPane,"Saved!");
             
        }
                
        //load accountArray method to save a/c number to String for use in payments/income form
       accountArray();
       //System.out.println("Save file array: " + accArr[0] +" "+ accArr[1] +" "+ accArr[2] +" "+ accArr[3]);    
       
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        //loadBtnActionPerformed(null);
        
        for(int i = 0; i < account.size(); i++){
        Account accTemp;
        Account acc = new Account();
        accTemp = account.get(i);
        
        if(jComboBox1.getSelectedItem().equals(accTemp.getAccNum())){
            //load data from AccountDetails.dat to Account class
                acc.setIBANNum(accTemp.getIBANNum());
                acc.setAccountPurpose(accTemp.getAccountPurpose());
                acc.setAccType(accTemp.getAccType());
                acc.setBICNum(accTemp.getBICNum());
                acc.setBankName(accTemp.getBankName());
                acc.setBankAdd(accTemp.getBankAdd());
                acc.setBankphone(accTemp.getBankphone());
                acc.setSig1(accTemp.getSig1());
                acc.setSig2(accTemp.getSig2());
                acc.setSig3(accTemp.getSig3());
                acc.setSig4(accTemp.getSig4());
                acc.setAccNum(accTemp.getAccNum());
                
                //set txt fields to entries from saved object
                accNumTxt.setText(accTemp.getIBANNum());
                accPurposeTxt.setText(accTemp.getAccountPurpose());
                bicNumTxt.setText(accTemp.getBICNum());
                nameTxt.setText(accTemp.getBankName());
                addressTxt.setText(accTemp.getBankAdd());
                phoneTxt.setText(accTemp.getBankphone());
                accTypeTxt.setText(accTemp.getAccType());
                sig1txt.setText(accTemp.getSig1());
                sig2Txt.setText(accTemp.getSig2());
                sig3Txt.setText(accTemp.getSig3());
                sig4Txt.setText(accTemp.getSig4());
                //add break here so once if statement is met, loop ends
                //otherwise doesn't work
                break;
        }
        else{
                accNumTxt.setText("");
                accPurposeTxt.setText("");
                bicNumTxt.setText("");
                nameTxt.setText("");
                addressTxt.setText("");
                phoneTxt.setText("");
                accTypeTxt.setText("");
                sig1txt.setText("");
                sig2Txt.setText("");
                sig3Txt.setText("");
                sig4Txt.setText("");
        }
      }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
        for (int i = 0; i < account.size(); i++) {
            Account ass1;
            ass1 = account.get(i);
            if (jComboBox1.getSelectedItem().toString().equals(ass1.getAccNum())) {
                
            
                account.remove(i);
            
                //create instance of Account object 
                Account acc = new Account();

                //add txt fields to Account
                acc.setIBANNum(accNumTxt.getText());
                acc.setAccountPurpose(accPurposeTxt.getText());
                acc.setAccType(accTypeTxt.getText());
                acc.setBICNum(bicNumTxt.getText());
                acc.setBankName(nameTxt.getText());
                acc.setBankAdd(addressTxt.getText());
                acc.setBankphone(phoneTxt.getText());
                acc.setSig1(sig1txt.getText());
                acc.setSig2(sig2Txt.getText());
                acc.setSig3(sig3Txt.getText());
                acc.setSig4(sig4Txt.getText());
                acc.setAccNum(jComboBox1.getSelectedItem().toString());

                //loadBtnActionPerformed(null);
                //add to arraylist
                account.add(i, acc);
                
                    }
            
        }
        //Save
                try{
                    ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("AccountDetails.dat"));


                    for(int i = 0; i < account.size(); i++){
                        out.writeObject(account.get(i));
                        //out.writeObject(acc);
                        //close stream

                       }
                     out.close();
                }
                catch(EOFException e){
                        //End of file always throws exception, do nothing with this
                        }
                catch(FileNotFoundException ev){
                        JOptionPane.showMessageDialog(null, "File Not Found Exception: "+ ev);
                        }
                catch(IOException evn){
                        JOptionPane.showMessageDialog(null, "IOException: "+ evn);
                        }
                JOptionPane.showMessageDialog(rootPane,"Saved!");
        
    }//GEN-LAST:event_updateBtnActionPerformed

    public String[] getAccArr() {
        return accArr;
    }

    public void setAccArr(String[] accArr) {
        this.accArr = accArr;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accNumLbl;
    private javax.swing.JTextField accNumTxt;
    private javax.swing.JLabel accPurposeLbl;
    private javax.swing.JTextField accPurposeTxt;
    private javax.swing.JLabel accTypeLbl;
    private javax.swing.JTextField accTypeTxt;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel bicNumLbl;
    private javax.swing.JTextField bicNumTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel sig1Lbl;
    private javax.swing.JTextField sig1txt;
    private javax.swing.JLabel sig2Lbl;
    private javax.swing.JTextField sig2Txt;
    private javax.swing.JLabel sig3Lbl;
    private javax.swing.JTextField sig3Txt;
    private javax.swing.JLabel sig4Lbl;
    private javax.swing.JTextField sig4Txt;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
