/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.orderofmalta;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class AssetsLiabilitiesForm extends javax.swing.JFrame {

    /**
     * Creates new form AssetsLiabilitiesForm
     */
    //create arrayList
    private ArrayList<AssetsLiabilities> assets;
    AssetsLiabilities ass;

    public AssetsLiabilitiesForm() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        assets = new ArrayList<AssetsLiabilities>();
        ass = new AssetsLiabilities();
        //load file on startup
        loadFile();
        //load jcombobox action on startup so initial year is read
        jComboBox1ActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        bankOpenLbl = new javax.swing.JLabel();
        bankCloseLbl = new javax.swing.JLabel();
        bankOpenTxt = new javax.swing.JTextField();
        bankCloseTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        creditOpenLbl = new javax.swing.JLabel();
        creditCloseLbl = new javax.swing.JLabel();
        creditOpenTxt = new javax.swing.JTextField();
        creditCloseTxt = new javax.swing.JTextField();
        postOpenLbl = new javax.swing.JLabel();
        postCloseLbl = new javax.swing.JLabel();
        postOpenTxt = new javax.swing.JTextField();
        postCloseTxt = new javax.swing.JTextField();
        cohLbl = new javax.swing.JLabel();
        vehicleValLbl = new javax.swing.JLabel();
        cohTxt = new javax.swing.JTextField();
        VehicleValTxt = new javax.swing.JTextField();
        buildingLbl = new javax.swing.JLabel();
        equipLbl = new javax.swing.JLabel();
        buildingTxt = new javax.swing.JTextField();
        equipTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        currentOverLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        currentOverTxt = new javax.swing.JTextField();
        bankLoanLbl = new javax.swing.JLabel();
        bankLoanTxt = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Assets"));

        bankOpenLbl.setText("Bank Opening Balance");

        bankCloseLbl.setText("Bank Closing Balance");

        bankOpenTxt.setText("0.00");

        bankCloseTxt.setText("0.00");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        creditOpenLbl.setText("Credit Union Opening Balance");

        creditCloseLbl.setText("Credit Union Closing Balance");

        creditOpenTxt.setText("0.00");

        creditCloseTxt.setText("0.00");

        postOpenLbl.setText("Post Office Opening Balance");

        postCloseLbl.setText("Post Office Closing Balance");

        postOpenTxt.setText("0.00");

        postCloseTxt.setText("0.00");

        cohLbl.setText("Closing Cash on Hand");

        vehicleValLbl.setText("Vehicles Value");

        cohTxt.setText("0.00");

        VehicleValTxt.setText("0.00");

        buildingLbl.setText("Buildings Value");

        equipLbl.setText("Equipment Value");

        buildingTxt.setText("0.00");

        equipTxt.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankOpenLbl)
                    .addComponent(bankOpenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditOpenLbl)
                    .addComponent(creditOpenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postOpenLbl)
                    .addComponent(cohLbl)
                    .addComponent(buildingLbl)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buildingTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(cohTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(postOpenTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankCloseLbl)
                    .addComponent(creditCloseLbl)
                    .addComponent(creditCloseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postCloseLbl)
                    .addComponent(vehicleValLbl)
                    .addComponent(bankCloseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipLbl)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(equipTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(VehicleValTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(postCloseTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankOpenLbl)
                            .addComponent(bankCloseLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bankOpenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankCloseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditOpenLbl)
                            .addComponent(creditCloseLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditOpenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(creditCloseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postOpenLbl)
                            .addComponent(postCloseLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postOpenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postCloseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cohLbl)
                            .addComponent(vehicleValLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cohTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VehicleValTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buildingLbl)
                            .addComponent(equipLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buildingTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Liabilities"));

        currentOverLbl.setText("Current Account Overdrawn");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        currentOverTxt.setText("0.00");

        bankLoanLbl.setText("Bank Loan");

        bankLoanTxt.setText("0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentOverLbl)
                    .addComponent(currentOverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bankLoanLbl)
                    .addComponent(bankLoanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(currentOverLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(currentOverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(bankLoanLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bankLoanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Year");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update Entry");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(updateBtn)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(642, 643));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //call loadFile() method to load file into arraylist
        //then if the selected year in combobox equals the year in the arraylist
        //show info and load info to AssetsLiabilities class
        AssetsLiabilities ass1 = new AssetsLiabilities();
        //loadFile();
        for (int i = 0; i < assets.size(); i++) {
            //
            AssetsLiabilities ass = assets.get(i);

            // JOptionPane.showMessageDialog(null,"jComboBox year: "+ jComboBox1.getSelectedItem() + " arraylist year: "+ ass.getYear());
            if (jComboBox1.getSelectedItem().equals(ass.getYear())) {

                //load data from AssetsLiabilities.dat to AssetsLiabilities class
                ass1.setBankOpenBal(ass.getBankOpenBal());
                ass1.setBankCloseBal(ass.getBankCloseBal());
                ass1.setCreditOpenBal(ass.getCreditOpenBal());
                ass1.setCreditCloseBal(ass.getCreditCloseBal());
                ass1.setPostOpenBal(ass.getPostOpenBal());
                ass1.setPostCloseBal(ass.getPostCloseBal());
                ass1.setCoh(ass.getCoh());
                ass1.setVehicleVal(ass.getVehicleVal());
                ass1.setBuildingVal(ass.getBuildingVal());
                ass1.setEquipVal(ass.getEquipVal());
                ass1.setOverdrawn(ass.getOverdrawn());
                ass1.setLoan(ass.getLoan());
                ass1.setYear(ass.getYear());

                //set txt fields to entries from saved object
                bankOpenTxt.setText(Double.toString(ass1.getBankOpenBal()));
                bankCloseTxt.setText(Double.toString(ass1.getBankCloseBal()));
                creditOpenTxt.setText(Double.toString(ass1.getCreditOpenBal()));
                creditCloseTxt.setText(Double.toString(ass1.getCreditCloseBal()));
                postOpenTxt.setText(Double.toString(ass1.getPostOpenBal()));
                postCloseTxt.setText(Double.toString(ass1.getPostCloseBal()));
                cohTxt.setText(Double.toString(ass1.getCoh()));
                VehicleValTxt.setText(Double.toString(ass1.getVehicleVal()));
                buildingTxt.setText(Double.toString(ass1.getBuildingVal()));
                equipTxt.setText(Double.toString(ass1.getEquipVal()));
                currentOverTxt.setText(Double.toString(ass1.getOverdrawn()));
                bankLoanTxt.setText(Double.toString(ass1.getLoan()));
                //add break here so once if statement is met, loop ends
                //otherwise doesn't work
                break;
            } else {
                bankOpenTxt.setText("0.00");
                bankCloseTxt.setText("0.00");
                creditOpenTxt.setText("0.00");
                creditCloseTxt.setText("0.00");
                postOpenTxt.setText("0.00");
                postCloseTxt.setText("0.00");
                cohTxt.setText("0.00");
                VehicleValTxt.setText("0.00");
                buildingTxt.setText("0.00");
                equipTxt.setText("0.00");
                currentOverTxt.setText("0.00");
                bankLoanTxt.setText("0.00");
            }

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void loadFile() {
        try {
            ObjectInputStream in = new ObjectInputStream(new FileInputStream("AssetsLiabilities.dat"));
            AssetsLiabilities assTemp;
            AssetsLiabilities ass;
            //clear arraylist
            assets.clear();

            while (true) {
                assTemp = (AssetsLiabilities) in.readObject();

                ass = new AssetsLiabilities();
                //load data from AssetsLiabilities.dat to AssetsLiabilities class
                ass.setBankOpenBal(assTemp.getBankOpenBal());
                ass.setBankCloseBal(assTemp.getBankCloseBal());
                ass.setCreditOpenBal(assTemp.getCreditOpenBal());
                ass.setCreditCloseBal(assTemp.getCreditCloseBal());
                ass.setPostOpenBal(assTemp.getPostOpenBal());
                ass.setPostCloseBal(assTemp.getPostCloseBal());
                ass.setCoh(assTemp.getCoh());
                ass.setVehicleVal(assTemp.getVehicleVal());
                ass.setBuildingVal(assTemp.getBuildingVal());
                ass.setEquipVal(assTemp.getEquipVal());
                ass.setOverdrawn(assTemp.getOverdrawn());
                ass.setLoan(assTemp.getLoan());
                ass.setYear(assTemp.getYear());

                /*//set txt fields to entries from saved object
                 bankOpenTxt.setText(Double.toString(ass.getBankOpenBal()));
                 bankCloseTxt.setText(Double.toString(ass.getBankCloseBal()));
                 creditOpenTxt.setText(Double.toString(ass.getCreditOpenBal()));
                 creditCloseTxt.setText(Double.toString(ass.getCreditCloseBal()));
                 postOpenTxt.setText(Double.toString(ass.getPostOpenBal()));
                 postCloseTxt.setText(Double.toString(ass.getPostCloseBal()));
                 cohTxt.setText(Double.toString(ass.getCoh()));
                 VehicleValTxt.setText(Double.toString(ass.getVehicleVal()));
                 buildingTxt.setText(Double.toString(ass.getBuildingVal()));
                 equipTxt.setText(Double.toString(ass.getEquipVal()));
                 currentOverTxt.setText(Double.toString(ass.getOverdrawn()));
                 bankLoanTxt.setText(Double.toString(ass.getLoan()));*/
                //add to arraylist
                assets.add(ass);
            }
            //JOptionPane.showMessageDialog(null,"Loaded!");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Class Not Found Exception: " + e);
        } catch (EOFException ex) {
            //end of file exception will be thrown when end of file reached
            //do nothing with this exception
            //JOptionPane.showMessageDialog(null, "End of File Reached");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "IOError: " + e);
        }
    }

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        //int numComboItems = jComboBox1.getItemCount();

        //create temp assetsliabilities object
        AssetsLiabilities ass = new AssetsLiabilities();

        //set values from form txtfields to doubles
        double bankOpen = Double.parseDouble(bankOpenTxt.getText());
        double bankClose = Double.parseDouble(bankCloseTxt.getText());
        double creditOpen = Double.parseDouble(creditOpenTxt.getText());
        double creditClose = Double.parseDouble(creditCloseTxt.getText());
        double postOpen = Double.parseDouble(postOpenTxt.getText());
        double postClose = Double.parseDouble(postCloseTxt.getText());
        double coh = Double.parseDouble(cohTxt.getText());
        double vehicle = Double.parseDouble(VehicleValTxt.getText());
        double building = Double.parseDouble(buildingTxt.getText());
        double equip = Double.parseDouble(equipTxt.getText());
        double currentOver = Double.parseDouble(currentOverTxt.getText());
        double bankLoan = Double.parseDouble(bankLoanTxt.getText());

        //add to AssetsLiabilities
        ass.setBankOpenBal(bankOpen);
        ass.setBankCloseBal(bankClose);
        ass.setCreditOpenBal(creditOpen);
        ass.setCreditCloseBal(creditClose);
        ass.setPostOpenBal(postOpen);
        ass.setPostCloseBal(postClose);
        ass.setCoh(coh);
        ass.setVehicleVal(vehicle);
        ass.setBuildingVal(building);
        ass.setEquipVal(equip);
        ass.setOverdrawn(currentOver);
        ass.setLoan(bankLoan);
        //set year as that of selected in the jComboBox
        ass.setYear(jComboBox1.getSelectedItem().toString());

        //add to arrayList
        assets.add(ass);

        //save
        try {
            ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("AssetsLiabilities.dat"));

            for (int i = 0; i < assets.size(); i++) {
                out.writeObject(assets.get(i));
            }
            //close stream
            out.close();
        } catch (EOFException e) {
            //End of file always throws exception, do nothing with this
        } catch (FileNotFoundException ev) {
            JOptionPane.showMessageDialog(null, "File Not Found Exception: " + ev);
        } catch (IOException evn) {
            JOptionPane.showMessageDialog(null, "IOException: " + evn);
        }
        JOptionPane.showMessageDialog(rootPane, "Saved!");


    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        //check if years in combobox match one in array list
        for (int i = 0; i < assets.size(); i++) {
            AssetsLiabilities ass1;
            ass1 = assets.get(i);
            if (jComboBox1.getSelectedItem().toString().equals(ass1.getYear())) {
                //remove object first
                assets.remove(i);
                //then re-add info
                AssetsLiabilities ass = new AssetsLiabilities();

                //set values from form txtfields to doubles
                double bankOpen = Double.parseDouble(bankOpenTxt.getText());
                double bankClose = Double.parseDouble(bankCloseTxt.getText());
                double creditOpen = Double.parseDouble(creditOpenTxt.getText());
                double creditClose = Double.parseDouble(creditCloseTxt.getText());
                double postOpen = Double.parseDouble(postOpenTxt.getText());
                double postClose = Double.parseDouble(postCloseTxt.getText());
                double coh = Double.parseDouble(cohTxt.getText());
                double vehicle = Double.parseDouble(VehicleValTxt.getText());
                double building = Double.parseDouble(buildingTxt.getText());
                double equip = Double.parseDouble(equipTxt.getText());
                double currentOver = Double.parseDouble(currentOverTxt.getText());
                double bankLoan = Double.parseDouble(bankLoanTxt.getText());

                //add to AssetsLiabilities
                ass.setBankOpenBal(bankOpen);
                ass.setBankCloseBal(bankClose);
                ass.setCreditOpenBal(creditOpen);
                ass.setCreditCloseBal(creditClose);
                ass.setPostOpenBal(postOpen);
                ass.setPostCloseBal(postClose);
                ass.setCoh(coh);
                ass.setVehicleVal(vehicle);
                ass.setBuildingVal(building);
                ass.setEquipVal(equip);
                ass.setOverdrawn(currentOver);
                ass.setLoan(bankLoan);
                //set year as that of selected in the jComboBox
                ass.setYear(jComboBox1.getSelectedItem().toString());

                //add to arrayList
                assets.add(i, ass);
                }
            }

                //save
                try {
                    ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("AssetsLiabilities.dat"));

                    for (int j = 0; j < assets.size(); j++) {
                        out.writeObject(assets.get(j));
                    }
                    //close stream
                    out.close();
                } catch (EOFException e) {
                    //End of file always throws exception, do nothing with this
                } catch (FileNotFoundException ev) {
                    JOptionPane.showMessageDialog(null, "File Not Found Exception: " + ev);
                } catch (IOException evn) {
                    JOptionPane.showMessageDialog(null, "IOException: " + evn);
                }
                JOptionPane.showMessageDialog(rootPane, "Saved!");

    
        
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssetsLiabilitiesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssetsLiabilitiesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssetsLiabilitiesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssetsLiabilitiesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssetsLiabilitiesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VehicleValTxt;
    private javax.swing.JLabel bankCloseLbl;
    private javax.swing.JTextField bankCloseTxt;
    private javax.swing.JLabel bankLoanLbl;
    private javax.swing.JTextField bankLoanTxt;
    private javax.swing.JLabel bankOpenLbl;
    private javax.swing.JTextField bankOpenTxt;
    private javax.swing.JLabel buildingLbl;
    private javax.swing.JTextField buildingTxt;
    private javax.swing.JLabel cohLbl;
    private javax.swing.JTextField cohTxt;
    private javax.swing.JLabel creditCloseLbl;
    private javax.swing.JTextField creditCloseTxt;
    private javax.swing.JLabel creditOpenLbl;
    private javax.swing.JTextField creditOpenTxt;
    private javax.swing.JLabel currentOverLbl;
    private javax.swing.JTextField currentOverTxt;
    private javax.swing.JLabel equipLbl;
    private javax.swing.JTextField equipTxt;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel postCloseLbl;
    private javax.swing.JTextField postCloseTxt;
    private javax.swing.JLabel postOpenLbl;
    private javax.swing.JTextField postOpenTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel vehicleValLbl;
    // End of variables declaration//GEN-END:variables
}
