/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ie.orderofmalta;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRPrintPage;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;
import java.io.InputStream;

/**
 *
 * @author admin
 */
public class OMFinancialsForm extends javax.swing.JFrame {

    /**
     * Creates new form OMFinancialsForm
     */
    public OMFinancialsForm() {
        //loadSeaGlassLF();
        initComponents();
        //automatically add unit name to jFrame on startup if unit saved previously
        loadUnitDetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitNameLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        paymentsBtn = new javax.swing.JMenuItem();
        viewMoniesInBtn = new javax.swing.JMenuItem();
        viewMoniesOutBtn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        unitDetailsMenuBtn = new javax.swing.JMenuItem();
        unitAccountsMenuBtn = new javax.swing.JMenuItem();
        asssetLiabilitiesBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        yTDReportBtn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        backupBtn = new javax.swing.JMenuItem();
        restoreBtn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        aboutBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        unitNameLbl.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        unitNameLbl.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1039, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ie/orderofmalta/omacLogo1.jpg"))); // NOI18N

        jMenu1.setText("Menu");

        jMenuItem1.setText("Receipts");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        paymentsBtn.setText("Payments");
        paymentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsBtnActionPerformed(evt);
            }
        });
        jMenu1.add(paymentsBtn);

        viewMoniesInBtn.setText("View Monies In");
        viewMoniesInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMoniesInBtnActionPerformed(evt);
            }
        });
        jMenu1.add(viewMoniesInBtn);

        viewMoniesOutBtn.setText("View Monies Out");
        viewMoniesOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMoniesOutBtnActionPerformed(evt);
            }
        });
        jMenu1.add(viewMoniesOutBtn);
        jMenu1.add(jSeparator1);

        unitDetailsMenuBtn.setText("Unit Details");
        unitDetailsMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitDetailsMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(unitDetailsMenuBtn);

        unitAccountsMenuBtn.setText("Unit Accounts");
        unitAccountsMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitAccountsMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(unitAccountsMenuBtn);

        asssetLiabilitiesBtn.setText("Unit Assets and Liabilities");
        asssetLiabilitiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asssetLiabilitiesBtnActionPerformed(evt);
            }
        });
        jMenu1.add(asssetLiabilitiesBtn);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reports");

        jMenuItem8.setText("Annual Financial Report");
        jMenu2.add(jMenuItem8);

        yTDReportBtn.setText("Financial Year To Date");
        yTDReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yTDReportBtnActionPerformed(evt);
            }
        });
        jMenu2.add(yTDReportBtn);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tools");

        backupBtn.setText("Back Up System");
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });
        jMenu3.add(backupBtn);

        restoreBtn.setText("Restore");
        restoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreBtnActionPerformed(evt);
            }
        });
        jMenu3.add(restoreBtn);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        aboutBtn.setText("About");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        jMenu4.add(aboutBtn);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(unitNameLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(unitNameLbl)
                .addGap(104, 104, 104)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );

        setSize(new java.awt.Dimension(1040, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void paymentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsBtnActionPerformed
        PaymentsForm form = new PaymentsForm();
        form.setVisible(true);
    }//GEN-LAST:event_paymentsBtnActionPerformed

    private void viewMoniesInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMoniesInBtnActionPerformed
        ViewMoniesIn form = new ViewMoniesIn();
        form.setVisible(true);
    }//GEN-LAST:event_viewMoniesInBtnActionPerformed

    private void unitAccountsMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitAccountsMenuBtnActionPerformed
        AccountForm form = new AccountForm();
        form.setVisible(true);
    }//GEN-LAST:event_unitAccountsMenuBtnActionPerformed

    private void yTDReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yTDReportBtnActionPerformed
        try
        {
            JasperReport jasperReport1 = null;
            JasperReport jasperReport2 = null;
            JasperPrint jasperPrint = null;
            JasperDesign jasperDesign = null;
            HashMap<String, Object> parameters = new HashMap<String, Object>();
            HashMap<String, Object> parameters2 = new HashMap<String, Object>();
            SimpleDateFormat formatter = new SimpleDateFormat("dd-mmm-yyyy");  
            //String today = formatter.format(new java.util.Date()); 
            //jasperDesign = JRXmlLoader.load("/Users/admin/Documents/HCCE/Semester 2/OOP/Projects2/OMFinancials/src/ie/orderofmalta/OMACYTDReport2.jrxml");
            //jasperReport = JasperCompileManager.compileReport(jasperDesign);
            
            //to get images to display in report, pass their relative path as input stream and add to HashMap
            //there must be one stream and one HashMap per image
            InputStream imgInputStream = this.getClass().getResourceAsStream("/reports/omacLogo.jpg");
            InputStream imgInputStream2 = this.getClass().getResourceAsStream("/reports/omacLogo.jpg");
            parameters.put("omacLogo", imgInputStream);
            parameters2.put("omacLogo", imgInputStream2);
            
            //load just the compiled jasper files, to save time
            //First merge the two jasper reports into one to get page1 and page 2 in same document
            InputStream jasper1 = this.getClass().getResourceAsStream("/reports/OmacYTDReportFinalpg1.jasper");
            InputStream jasper2 = this.getClass().getResourceAsStream("/reports/OmacYTDReportFinalpg2.jasper");
            
                
            //jasperReport1 = (JasperReport) JRLoader.loadObjectFromFile(jasper1);
            //jasperReport2 = (JasperReport) JRLoader.loadObject(jasper2);
            //jasperReport1 = (JasperReport) JRLoader.loadObjectFromFile(getClass().getResourceAsStream("/src/ie/orderofmalta/OMACYTDReportFinalpg1.jasper"));
            //jasperReport2 =(JasperReport) JRLoader.loadObjectFromFile(getClass().getResource("/src/ie/orderofmalta/OMACYTDReportFinalpg2.jasper").getFile());
            
            JasperPrint jp1 = JasperFillManager.fillReport(jasper1, parameters,new JRBeanCollectionDataSource(ie.orderofmalta.BeanFactory.getCalcs()));
            JasperPrint jp2 = JasperFillManager.fillReport(jasper2, parameters2, new JRBeanCollectionDataSource(ie.orderofmalta.BeanFactory.getCalcs()));
            
            List pages = jp2 .getPages();
            for (int j = 0; j < pages.size(); j++) {
            JRPrintPage object = (JRPrintPage)pages.get(j);
            jp1.addPage(object);
//            jp1.setName(unitNameLbl.getText() + " - Financial Year To Date - " + today );

    }
            JasperViewer.viewReport(jp1, false);

        }
        catch(Exception ex)
        {
            System.out.println("EXCEPTION: "+ex.getMessage() + ex);
        }
    }//GEN-LAST:event_yTDReportBtnActionPerformed

    private void unitDetailsMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitDetailsMenuBtnActionPerformed
        //display UnitDetailsForm
        UnitDetailsForm form = new UnitDetailsForm();
        form.setVisible(true);
    }//GEN-LAST:event_unitDetailsMenuBtnActionPerformed

    private void asssetLiabilitiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asssetLiabilitiesBtnActionPerformed
        AssetsLiabilitiesForm form = new AssetsLiabilitiesForm();
        form.setVisible(true);
    }//GEN-LAST:event_asssetLiabilitiesBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ReceiptsForm form = new ReceiptsForm();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        About form = new About();
        form.setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void viewMoniesOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMoniesOutBtnActionPerformed
        ViewMoniesOut form = new ViewMoniesOut();
        form.setVisible(true);
    }//GEN-LAST:event_viewMoniesOutBtnActionPerformed

    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
        ZipOutPut zip = new ZipOutPut();
        zip.createZip();
    }//GEN-LAST:event_backupBtnActionPerformed

    private void restoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreBtnActionPerformed
        ZipInput zip = new ZipInput();
        zip.loadZip();
    }//GEN-LAST:event_restoreBtnActionPerformed

    public void loadUnitDetails(){
        //add unit name to JFrame on startup, assuming unit details file previously saved
        
        
        try{
            ObjectInputStream in = new ObjectInputStream(new FileInputStream("UnitDetails.dat"));
            
            try{
                
                    //Calculations calc = new Calculations();
                    UnitDetails tempDetails;
                    tempDetails = (UnitDetails) in.readObject();
                    //calc.setUnit(tempDetails.getUnit());
                    unitNameLbl.setText(tempDetails.getUnit());
                    in.close();
                    
                
                
            }
            
            catch(ClassNotFoundException ev){
                JOptionPane.showMessageDialog(null, "Class Not Found Exception: "+ ev);
                }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, "IO Exception "+ e);
                }
        }
            catch(FileNotFoundException ev){
                JOptionPane.showMessageDialog(null, "File Not Found Exception: "+ ev);
                }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, "IO Exception "+ e);
                }
    }

    public static String getUnitNameLbl() {
        return unitNameLbl.toString();
    }

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OMFinancialsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OMFinancialsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OMFinancialsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OMFinancialsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OMFinancialsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutBtn;
    private javax.swing.JMenuItem asssetLiabilitiesBtn;
    private javax.swing.JMenuItem backupBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem paymentsBtn;
    private javax.swing.JMenuItem restoreBtn;
    private javax.swing.JMenuItem unitAccountsMenuBtn;
    private javax.swing.JMenuItem unitDetailsMenuBtn;
    public static javax.swing.JLabel unitNameLbl;
    private javax.swing.JMenuItem viewMoniesInBtn;
    private javax.swing.JMenuItem viewMoniesOutBtn;
    private javax.swing.JMenuItem yTDReportBtn;
    // End of variables declaration//GEN-END:variables
}
