/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ie.orderofmalta;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ViewMoniesOut extends javax.swing.JFrame {

    /**
     * Creates new form ViewMoniesOut
     */
    
    private DefaultTableModel model;
    private ArrayList<Payments> rec;
    
    public ViewMoniesOut() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();
        jTable1.setAutoCreateRowSorter(true);
        rec = new ArrayList<Payments>();
        loadAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        titleLbl.setText("All Payments Accounts");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Select Year");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Account No", "Category", "Amount", "Receipt No", "Invoice No", "Cheque No", "Transaction Type", "Note", "Cleared"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(deleteBtn))
                    .addComponent(titleLbl)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1011, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void loadAll(){
        try {
            ObjectInputStream in = new ObjectInputStream(new FileInputStream("PaymentsPosted.dat"));
            Payments temp;
            //Receipts temp2;
            
            while (true) {
                temp = (Payments) in.readObject();
                rec.add(temp);
                
                //String amount = Double.toString(temp.getAmount());
                //model.addRow(new String[]{temp.getDate(), temp.getAccount(), temp.getCategory(), amount, temp.getReceipt(), temp.getInvoice(),
                //temp.getCheque(), temp.getLodgement(), temp.getNote()});
                //model.setValueAt(true, WIDTH, 9);
                
            }
  
        }
            
            

         catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Class Not Found Exception: " + e);
        } catch (EOFException ex) {
            //end of file exception will be thrown when end of file reached
            //do nothing with this exception
            //JOptionPane.showMessageDialog(null, "End of File Reached");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "IOError: " + e);
        }
        
        jComboBox1ActionPerformed(null);
            
    }
    
    
    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Table is empty");
            } else {
                JOptionPane.showMessageDialog(rootPane, "You must select a row");
            }
        } else {
            int x = JOptionPane.showConfirmDialog(rootPane,"Are you sure you want to delete?", "choose one", JOptionPane.YES_NO_OPTION);
            if(x == 0){
                //delete from table row and arraylist
                rec.remove(jTable1.getSelectedRow());
                model.removeRow(jTable1.getSelectedRow());

                //resave so deleted items wont show up on startup anymore
                //save
                try {
                    ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("PaymentsPosted.dat"));

                    for (int i = 0; i < rec.size(); i++) {
                        out.writeObject(rec.get(i));
                    }
                    //close stream
                    out.close();
                } catch (EOFException e) {
                    //End of file always throws exception, do nothing with this
                } catch (FileNotFoundException ev) {
                    JOptionPane.showMessageDialog(null, "File Not Found Exception: " + ev);
                } catch (IOException evn) {
                    JOptionPane.showMessageDialog(null, "IOException: " + evn);
                }
                //JOptionPane.showMessageDialog(null, "Added to posting area");
            }

        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        model.setRowCount(0);
        for (int i = 0; i < rec.size(); i++) {
            Payments temp;
            temp = (Payments) rec.get(i);
            String year = temp.getDate().substring(temp.getDate().length()-4, temp.getDate().length());
        
            if (jComboBox1.getSelectedItem().equals(year)) {
                
                String amount = Double.toString(temp.getAmount());
                model.addRow(new String[]{temp.getDate(), temp.getAccount(), temp.getCategory(), amount, temp.getReceipt(), temp.getInvoice(),
                temp.getCheque(), temp.getTransactionType(), temp.getNote()});
            }
        }
        //loop through arraylist and add checkbox tick to each line
            for(int i = 0; i < model.getRowCount(); i++){
                if(jTable1.getRowCount() != 0){
                   model.setValueAt(true, i, 9);    
                }
             }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMoniesOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMoniesOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMoniesOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMoniesOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMoniesOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
